### ISSUE TITLE
An error happened while trying to display this block You canopen an issueorremove this block

### ISSUE THREAD

**Issue by McScience** [ThemeFuse/Brizy#1509] opened 2019-09-20 04:14 UTC
An error happened while trying to display this block
You canopen an issueorremove this block

why?

**Comment by NataliaBB** [comment] 2019-10-16 12:27
Hello!
The issue is fixed in the latest updates.

Natalia

**Comment by NataliaBB** [comment] 2019-10-16 12:27
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Closed by NataliaBB** 2019-10-16 12:27 UTC
Labels: Issue Fixed
