### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by crystalcotter** [ThemeFuse/Brizy#1241] opened 2019-04-01 11:40 UTC
Images are not showing up on page

**Comment by elongnec** [comment] 2019-04-01 22:19
I am having the same issue, and can no longer upload new images, upload page is blank.

**Comment by NataliaBB** [comment] 2019-04-02 10:05
Hello @crystalcotter @elongnec 
What plugins version do you have? The images are displayed in the preview mode? 
Please check if the PHP gd function is enabled. 
If yes, and images are still not uploaded in the editor, please give me a short message on our facebook chat 
Please, insert the issue number in the  message: 1241
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by crystalcotter** [comment] 2019-04-02 12:09
Please disregard this problem.  I deactivated everything and reinstalled
everything and It is working fine.  My two thoughts on the problem were
either I didn't give it enough time to show up, or there was a glitch with
the initial installation.  Thanks for reaching out.

**Comment by NataliaBB** [comment] 2019-04-02 13:04
Hey @crystalcotter  - thanks for updating me! If you have any other issue please write here or for emergencies issue - please send us a message via our facebook chat. 

Waiting for a reply from @elongnec 

Cheers!

**Comment by elongnec** [comment] 2019-04-02 16:13
@NataliaBB I was able to solve my issue as well by installing a different theme. Is there a recommended theme to use that works best with Brizy? Each theme that I've used has had a different problem associated with it when implementing Brizy front-end editing.

**Comment by NataliaBB** [comment] 2019-04-02 16:39
Hello @elongnec 
We recommend Astra, Ocean WP, Twenties, The Core. What themes did you have installed and had problems with Brizy?
Thanks for reporting.
Natalia

**Comment by elongnec** [comment] 2019-04-02 18:56
Thanks, @NataliaBB ! I will switch to one of those themes. I was using Gogo (which was giving me the image upload problems) and before that was Zita (was giving me embed problems).

**Comment by andonivianez** [comment] 2019-04-03 09:10
I´m having the same problem with Brizy; I´ve tried on 2 fresh WP installations and the same thing happened; 404 and 500 errors in console with images.

**Comment by GabrielAnca** [comment] 2019-04-03 20:27
This happened to me too. In my case it was caused by [TranslatePress](https://wordpress.org/plugins/translatepress-multilingual/): The page was configured to be Spanish, but the active language in the site was English, so the images were uploaded to the English section by default, and couldn't be loaded from the Spanish page.

**Comment by andonivianez** [comment] 2019-04-03 20:37
My problem was with php-imagick, that wasn´t installed on my server.

**Comment by NataliaBB** [comment] 2019-04-17 13:32
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-04-17 13:32 UTC
Labels: bug, needs feedback
