### ISSUE TITLE
contact form - only capital letters

### ISSUE THREAD

**Issue by rsdesignsnl** [ThemeFuse/Brizy#1004] opened 2018-12-19 15:44 UTC
I can only do capital letters in the contact form. How can I change it? If I choose a different lettering it still stays in capital letters. 
If people fill in the form it gets in my mail like that too,.. I need some help!

**Comment by maxval94** [comment] 2018-12-27 14:00
Hi @rsdesignsnl!
Check out this demo here's how you can change the style of the letters https://jmp.sh/7pclhlL
In case you cannot change it than it could be caused by the theme styling
I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Thank you!
Maxim

**Closed by maxval94** 2018-12-27 14:00 UTC
