### ISSUE TITLE
Same issue as the precedent one

### ISSUE THREAD

**Issue by jmd1010** [ThemeFuse/Brizy#1510] opened 2019-09-20 17:13 UTC
I just installed the new upgrade to brizy 10.86

and I get the message remove block when trying to edit it. 

I had the same issue after the upgrade 2 days ago.

I use Brizyy pro. My site is outhiink.com

**Comment by NataliaBB** [comment] 2019-10-16 12:29
Hello Jean @jmd1010 
The issue is fixed in the latest Brizy updates.

Regards, Natalia

**Comment by NataliaBB** [comment] 2019-10-16 12:29
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Closed by NataliaBB** 2019-10-16 12:29 UTC
