### ISSUE TITLE
Image size in the editor is not the same as in the preview!

### ISSUE THREAD

**Issue by melamedh** [ThemeFuse/Brizy#105] opened 2018-06-07 03:23 UTC
Hey Guys,

When adding an image in the editor, then it takes the whole screen. But in the preview page, it looks just fine.
This must be fixed.

Cheers.

**Comment by bagrinsergiu** [comment] 2018-06-07 09:09
Hi @melamedh ,

Can you give me a Page URL or a screenshot?

Thanks for reporting
Sergiu

**Comment by melamedh** [comment] 2018-06-07 16:09
Here you go:
![outsie the editor](https://user-images.githubusercontent.com/40013956/41111995-eaef2ea2-6a7d-11e8-9fad-8d4bbc6e78e4.png)
![outsie the editor](https://user-images.githubusercontent.com/40013956/41112006-f2331296-6a7d-11e8-9bb4-8308fbb339bd.png)

**Comment by bagrinsergiu** [comment] 2018-06-10 12:58
I can't reproduce this issue.

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment] 2018-06-29 09:34
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu

**Closed by bagrinsergiu** 2018-06-29 09:34 UTC
Labels: bug, needs feedback
