### ISSUE TITLE
WooCommerce not working correctly with Brizy

### ISSUE THREAD

**Issue by petrakosecova** [ThemeFuse/Brizy#797] opened 2018-10-29 15:14 UTC
Over one week I am trying to solve my issues regarding WooCommerce and Brizy.

2 major issues

Woocommerce cart - when it is empty, it displays only default theme/SHOP page which I am not able to edit (despite I hit the button edit with brizy, despite the brizy theme is selected, it shows only default theme and totally uneditable).

Woocommerce items - I am able to insert product/products, collections and so on into PAGES but I am not able to edit Woocommerce PRODUCTs with Brizy - it opens the editor, I make my design, it seems like it saves the template but after hitting the preview I got only gray screen and nothing happens.

It would be awesome if for example - inserted collection of products to some page would direct to PAGES with inserted products but it directs to PRODUCTS and then it is not working at all.

I have purchased Brizy PRO some time ago to design my woocommerce store and it seems to be useless completely at this moment. Not to mention I am trying to solve this situation with customer support over one week and absolutely nothing :-(

**Comment by NataliaBB** [comment] 2018-10-30 08:29
Hello Petra @petrakosecova 

Natalia here!
Sorry for the inconvenience caused by our editor. As I  mentioned in my chat message - we need a little more time to solve this question. I will try to hurry the team regarding this issue.

Thanks for understanding.

Regards, Natalia

**Comment by NataliaBB** [comment] 2019-06-05 08:44
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-06-05 08:44 UTC
Labels: bug
