### ISSUE TITLE
Row and Block settings menu icons broken in Chrome

### ISSUE THREAD

**Issue by sondes** [ThemeFuse/Brizy#1115] opened 2019-02-08 18:59 UTC
The icons in the row settings menu are broken when AdBlock Plus extension is active in Google Chrome Version 72.0.3626.96 (Official Build)  #(64-bit).

![brizy - buggy behavior in google chrome cause icons to not be visible](https://user-images.githubusercontent.com/913448/52499195-1773d000-2b98-11e9-95dd-8ed8d55ef296.png)

**Comment by NataliaBB** [comment] 2019-02-12 09:22
Hello @sondes 
The problem is not in AdBlock extension. We need to check why icons and images are not displayed in the editor page. 
So, give us a PM via our facebook chat. Please mention the issue number - #1115 

My best Regards, Natalia

**Comment by NataliaBB** [comment] 2019-02-12 09:23
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-02-12 09:23 UTC
Labels: bug, needs feedback
