### ISSUE TITLE
CSS panel tags disappering

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1194] opened 2019-03-14 20:35 UTC
I put two CSS rules into my custom CSS and when I revisit the panel the second rule is hidden… only shows up when I click into the panel

https://screen.maxziebell.de/20190314-ezraz.mp4

Great feature otherwise! I found it to be a bit hard to see live changes as the "drawer" is overlapping the content and the brizy content aware tooltip stays open …

https://screen.maxziebell.de/20190314-etc2q.png

**Comment by NataliaBB** [comment] 2019-03-15 09:48
Hey @MaxZiebell 
I've tested at my end a random code, and I couldn't reproduce it since the entire code was visible.
In any case, I've open an issue for the team with this request. We'll check and eventually fix it. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment] 2019-03-27 15:52
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-03-27 15:52 UTC
Labels: bug
