### ISSUE TITLE
Toolbox mixed up after upgrading to 0.0.8

### ISSUE THREAD

**Issue by firstandlast1966** [ThemeFuse/Brizy#675] opened 2018-09-28 20:10 UTC
Hi, I upgraded Brizy to 0.0.8. I have the Generate Press theme.

On loading a page to edit it seems the Toolbox has got a bit mixed up. When I drag a text element onto the page it puts a button there instead! When I drag a button element on it puts a form and the form element is the text. The image shows that the Form element is in the place of the Text and that is causing the issue.

![brizy wrong](https://user-images.githubusercontent.com/40405177/46231105-a1966700-c362-11e8-9127-d6c288930d85.JPG)

**Comment by firstandlast1966** [comment] 2018-09-28 21:33
I think this problem has stemmed from the 1.0.35 update as on a site  I have just Brizy free on, when I updated that to 1.0.35 the embed element is the first in the list.

**Comment by willhousecreative** [comment] 2018-09-29 00:48
I can confirm that dragging a text blog creates a button 
![text-to-button](https://user-images.githubusercontent.com/19369150/46238948-852c0780-c32d-11e8-84fd-7aa70e874aaf.gif)

**Comment by peleroberts** [comment] 2018-09-29 15:16
Can confirm, updated one of my sites after seeing this. Holding off from updating the rest.

**Comment by TCDTRapla** [comment] 2018-09-30 13:52
Hi! Same problem: I am stuck in my job ...

- Form =>Text

- Text =>Button

- Button => Form

**Comment by TCDTRapla** [comment] 2018-10-01 15:35
Problem fixed with the update Brizy Free Version 1.0.36

**Comment by peleroberts** [comment] 2018-10-01 15:40
Confirmed

**Comment by NataliaBB** [comment] 2018-10-01 20:42
Hi Everyone! @firstandlast1966, @willhousecreative, @cuongtalentccc, @peleroberts, @cmbc58, @TCDTRapla!

Sorry for this inconvenience caused by our developers who rushed to release the new update :) 
This issue has been fixed in today's update. 1.0.36.

My Best Regards, Natalia

**Comment by NataliaBB** [comment] 2018-10-01 20:42
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2018-10-01 20:42 UTC
