### ISSUE TITLE
Tabs - "Our Features and Services" Block on Mobile, unable to center heading

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1138] opened 2019-02-16 05:09 UTC
When viewing the Mobile version of the Tabs block "Our Features and Services", there is no way to center the Tab Headings text.
![image](https://user-images.githubusercontent.com/6964524/52894872-cfd6ef00-31fc-11e9-9046-248ae6bb6261.png)

**Comment by NataliaBB** [comment] 2019-02-18 15:46
Hello Dennis! @DenMurphy 
Natalia here. 
I'm afraid I can not reproduce this issue, since I do have the align option in the block, at my end
https://jmp.sh/ZpdtUQs

Did I miss something, can I check your page by myself?
Please send me a message via our facebook chat.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by DenMurphy** [comment] 2019-02-18 18:29
Hi Natalia, look up to the word FEATURE 3. I’m trying to align the header.
    	
    	

    	Regards, Dennis MurphySenior Control Systems Engineer0428 500 880
    
  




On Tue, Feb 19, 2019 at 1:46 AM +1000, "NataliaBB" <notifications@github.com> wrote:












Hello Dennis! @DenMurphy

Natalia here.

I'm afraid I can not reproduce this issue, since I do have the align option in the block, at my end

https://jmp.sh/ZpdtUQs


Did I miss something, can I check your page by myself?

Please send me a message via our facebook chat.





Thank you!

Regards, Natalia

**Comment by DenMurphy** [comment] 2019-02-18 20:26
<https://dennismurphy.biz/> 


Dennis Murphy 


Electrical / Control Systems Engineer 


M:  <tel:0428500880> 0428 500 880


E:  <mailto:hello@dennismurphy.biz> hello@dennismurphy.biz | W:  <https://dennismurphy.biz/> dennismurphy.biz



 <https://www.facebook.com/DenMurphy> 

 <https://twitter.com/denmurphy> 

 <https://www.linkedin.com/in/dennismurphy/> 


Experienced Electrical & Control Systems Engineer specialising in industrial control system commissioning and security, website development, hosting, email migration, marketing, and event management.

**Comment by DenMurphy** [comment] 2019-02-20 09:04
Hi @NataliaBB, look up to the word "FEATURE 3" on that screen grab you sent. I’m trying to align the Title in the Tab itself. 

![screengrab](https://user-images.githubusercontent.com/6964524/53079518-57e12f80-3542-11e9-92e4-f2df26f0984a.png)

**Comment by NataliaBB** [comment] 2019-02-21 15:58
Hi Dennis! @DenMurphy 
Got it. Already made an issue for the team regarding this request.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment] 2019-02-21 15:58
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-02-21 15:58 UTC
Labels: needs feedback
