### ISSUE TITLE
Brizy not able to Preview pages in MAMP (PRO) Environment

### ISSUE THREAD

**Issue by hbx5555** [ThemeFuse/Brizy#170] opened 2018-06-14 09:53 UTC
Tried building pages in MAMP PRO local Word Press environment and while Brizy worked normally and allowed building pages the Preview did not work nor the attempt to see the pages when saved. I suspect it has to do with path-names structure, and the installation tested used the sub-directory mode, in which you create a special directory per WP instance (there is also one app that can use the root, but that one is not available on my system). All other page builders work fine in this mode. Tested with few themes as the base

**Comment by bagrinsergiu** [comment] 2018-06-14 09:59
Hi Chaim,

Thanks for letting us know, we are looking into it.

It is working fine on MAMP Free we 3 Macs in our office. Plan to test on Pro version. 

Thanks for reporting 
Sergiu

**Comment by marcellefter** [comment] 2018-06-14 12:11
Hi Chaim,

Can you give more details about MAMP PRO config(php version, apache or nginx etc.)?

Thanks
Marcel

**Comment by hbx5555** [comment] 2018-06-15 13:50
I am using MAMS Pro 4.5 , WP 4.9.6   with PHP 7.2.1, Apache Server.  Path is :  ...\documents\brizy-test   and page path looks like:   http://brizy-2:8888/test-brizy     (not localhost - that one is used). Latest Brizy version of course

**Comment by bagrinsergiu** [comment] 2018-06-21 06:52
Hi,

I received this issue 2-3 times but i can't reproduce it. I tested on 3 different MacBook + iMac on Mamp Free and Pro. Can you give me a teamviewer account in order to investigate this issue on your side?

Thanks for reporting
Sergiu

**Comment by NataliaBB** [comment] 2018-10-09 12:44
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2018-10-09 12:44 UTC
Labels: bug
