### ISSUE TITLE
very slow editing/updating

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1177] opened 2019-03-06 17:00 UTC
Any idea why editing and updating is super slow?  Anything I can do to improve this?

**Comment by NataliaBB** [comment] 2019-03-11 12:02
Hello @lilsurepbc 
What exactly means super slow? Does it take couple of minutes? 
It can be caused by other installed plugins, server or PHP environment.  

Send me please an 
Please send me a message via our Facebook chat and I will do some tests with the editor.
Please mention the issue number inside your message - #1177

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment] 2019-03-11 12:02
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-03-11 12:02 UTC
Labels: needs feedback
