### ISSUE TITLE
[BUG][URGENT] - Pages made with Brizy can not be displayed in Safari.

### ISSUE THREAD

**Issue by yudikondo** [ThemeFuse/Brizy#1537] opened 2019-10-22 12:20 UTC
**Everybody with Apple devices can not use any website make with Brizy.**
The page load is too slow and the scroll crash the page.
No problems with other browsers, Android, Mozilla and Edge works fine.
Please solve immediately, because we can not deploy any website with this problem.

**Comment by SmartOwlcrew** [comment] 2019-10-31 13:44
Seams that Brizy team does not care about this issue anymore. It is visible that they provide updates for different futures however there is still a huge BUG

**Comment by bagrinsergiu** [comment] 2020-02-03 08:22
Duplicate of # https://github.com/ThemeFuse/Brizy/issues/1535

**Closed by bagrinsergiu** 2020-02-03 08:22 UTC
