### ISSUE TITLE
Brizy on MacOS

### ISSUE THREAD

**Issue by blitzgeek** [ThemeFuse/Brizy#106] opened 2018-06-07 10:25 UTC
Is someone else using Brizy on a Mac? 
I always nearly run out of memory, no matter if I use firefox or chrome.
I can't use the global options for colors or fonts, cause no changes were saved. And again, no matter if I use firefox or chrome.
Did i miss something elemental?
Maybe this has to do with Brizy too:
Yesterday i had problems to reach the test-site i'm working on with Brizy, cause i was misinterpreted as "bad guy" doing Bruteforce attacks.
This is what siteground said:
"Your IP made a lot of requests to admin-ajax.php on xxx.com, which is why the issue was experienced."

**Comment by bagrinsergiu** [comment] 2018-06-07 10:55
Hi @blitzgeek,

Sergiu from Brizy here. Sorry for the inconvenience.

Can you give me more details about WP Version Plugin Version Site URL (if it is online)? 

Thanks for reporting.

**Comment by bagrinsergiu** [comment] 2018-06-07 10:57
Q: Maybe this has to do with Brizy too:
Yesterday i had problems to reach the test-site i'm working on with Brizy, cause i was misinterpreted as "bad guy" doing Bruteforce attacks.
This is what siteground said:
"Your IP made a lot of requests to admin-ajax.php on xxx.com, which is why the issue was experienced."

A: We use Brizy API for assets and image resize. Can you give me a screen with this message to contact siteground for more details.

**Comment by bagrinsergiu** [comment] 2018-06-07 11:00
Q: I can't use the global options for colors or fonts, cause no changes were saved. And again, no matter if I use firefox or chrome.

A: This can be a big issue on our side. We read 2-3 comments about this but i can't reproduce it. Can you give me more details about server side tech data ( Server, PHP Version, MySQL Version)

This issue is veri important for us to undestand what it is happen.

Thank you.

**Comment by bagrinsergiu** [comment] 2018-06-07 11:02
Q: Is someone else using Brizy on a Mac?
I always nearly run out of memory, no matter if I use firefox or chrome.

A: We have 3 iMacs and 4 Macbook in our offices. I want to check this issue on your side but i don't know how maybe TeamViewer?

**Comment by blitzgeek** [comment] 2018-06-07 11:41
Hi Sergiu,
sure. WP Version 4.9.6, Brizy Version 1.0.8 and GeneratePress 2.1.2.
The URL is https://improatwork.blitzdemo.space/ (just a playground yet)
A screenshot is hard to reproduce, because i can't manipulate a brute force attack. Seems that they implement something new, maybe this helps a bit:
https://www.siteground.com/blog/new-anti-bot-ai/
Server
Apache(?), PHP Version 7.1.17, MySQL server version: 5.6.36-82.1

**Comment by bagrinsergiu** [comment] 2018-06-07 13:21
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.

**Comment by blitzgeek** [comment] 2018-06-07 14:10
Done (https://www.facebook.com/sergiubagrin)

**Comment by bagrinsergiu** [comment] 2018-06-07 14:32
Sorry but i can't find it. Can you send me the FB Link?

**Comment by blitzgeek** [comment] 2018-06-07 14:39
Sender is "Freddie May" if this helps.

**Comment by bagrinsergiu** [comment] 2018-06-07 15:11
Thanks

**Comment by blitzgeek** [comment] 2018-06-07 15:27
Hm.
It's Siteground, isn't it one of your partners?
What can i do now?

**Comment by bagrinsergiu** [comment] 2018-06-07 15:29
I need to discuss with Siteground. You can build pages but don't change globals. After Update Will be possible to add your globals.

**Comment by bagrinsergiu** [comment] 2018-06-07 15:33
Is someone else using Brizy on a Mac?
I always nearly run out of memory, no matter if I use firefox or chrome.

Can you give me more details about this? Can you give me a screen with details?
Thanks

**Comment by blitzgeek** [comment] 2018-06-07 16:03
![brizy-on-chrome-activity](https://user-images.githubusercontent.com/10080048/41111693-0d7fa060-6a7d-11e8-8365-c19b7dcc47fb.jpg)

**Comment by bagrinsergiu** [comment] 2018-06-12 07:17
Hi @blitzgeek 

In last update 1.0.10 we added a fix for this issue. Can you confirm if it is working with last changes?

Thanks

**Comment by NataliaBB** [comment] 2018-10-09 12:14
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2018-10-09 12:14 UTC
Labels: bug
