### ISSUE TITLE
[Defect][URGENT ISSUE ] - Brizy does not work in Safari.  still not fixed for two month 

### ISSUE THREAD

**Issue by SmartOwlcrew** [ThemeFuse/Brizy#1539] opened 2019-10-24 10:40 UTC
Hi Brizy Team, 

We need to ask for a help from your side.

On **Apple devices** it is not possible to use a website made with Brizy .
The page load is critically slow and the scroll crash the page. The images disappears and reoccurs randomly with fleshing effect. 
Other browsers, Android, Mozilla and Edge works without issues.
Please solve this issue, as it affects all IPhone, IPad, MAC users and it's been already two month with no solution on this 

Regards,
Ross

**Comment by yudikondo** [comment] 2019-10-24 12:53
https://www.facebook.com/groups/brizy/

Dimitrie Baitanciuc:
_- Dianne Vita the guys are working on the problem. We didn t figure it out yet. Don t back down anything on the plugon side only. It is possible you will break your website.
If you have a full back up of an earlier version inclduing wordpress, plugons, everytjing. Then that might work, but only swithching Brizy to an older version is not the way to go.
Sit tight my colleagues are on it.. a fix is coming._

**Comment by SmartOwlcrew** [comment] 2019-10-24 13:45
Hi @yudikondo , Thank you for the feedback.
 Hope someone from Brizy Team will also update this defect with the feedback about current status. 

This issue was reported about two month ago. Still not fixes. It is not clear what might be wrong from the back end side as some websites does not have this defects. 
We tried to change themes and to inactivate plugins, however it was not possible to resolve this concern

**Comment by yudikondo** [comment] 2019-10-24 14:18
We have the same problem here: https://www.venoclin.com.br/
We are waiting the fix too.

I started this post, but apparently the Facebook Group is more active to answer questions.
https://github.com/ThemeFuse/Brizy/issues/1537

**Comment by bagrinsergiu** [comment] 2020-02-03 08:23
Duplicate of # https://github.com/ThemeFuse/Brizy/issues/1535

**Closed by bagrinsergiu** 2020-02-03 08:23 UTC
