### ISSUE TITLE
Issue updating Version 1.0.83 

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#1506] opened 2019-09-18 20:06 UTC
When I update Brizy Version 1.0.83 it crashes the page design and I have to go in and manually edit the page again with Brizy once and it seems to fix sometimes...
![image](https://user-images.githubusercontent.com/11094497/65181965-3b509b80-da2e-11e9-8781-551572fa9906.png)

**Comment by curiousprojects** [comment] 2019-09-18 20:09
Also the Facebook Page Embed is not loading when page is published.

**Comment by NataliaBB** [comment] 2019-10-16 09:32
Hello Bill!
The issue is fixed.

Regards. Natalia

**Comment by NataliaBB** [comment] 2019-10-16 09:32
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Closed by NataliaBB** 2019-10-16 09:32 UTC
