### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Twig_Loader_Array' not found

### ISSUE THREAD

**Issue by Brucekib** [ThemeFuse/Brizy#1175] opened 2019-03-06 06:13 UTC
Hi,

I started getting this error on the website www.wrappedup.co.za.

Fatal error: Uncaught Error: Class 'Twig_Loader_Array' not found in /usr/www/users/wrappeb/wp-content/plugins/brizy/twig-engine.php:34 Stack trace: #0 /usr/www/users/wrappeb/wp-content/plugins/brizy/public/main.php(355): Brizy_TwigEngine::instance('/usr/www/users/...') #1 /usr/www/users/wrappeb/wp-includes/class-wp-hook.php(286): Brizy_Public_Main->insert_page_head('') #2 /usr/www/users/wrappeb/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /usr/www/users/wrappeb/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /usr/www/users/wrappeb/wp-includes/general-template.php(2668): do_action('wp_head') #5 /usr/www/users/wrappeb/wp-content/plugins/oxygen/component-framework/oxygen-main-template.php(13): wp_head() #6 /usr/www/users/wrappeb/wp-includes/template-loader.php(77): include('/usr/www/users/...') #7 /usr/www/users/wrappeb/wp-blog-header.php(19): require_once('/usr/www/users/...') #8 /usr/www/users/wrappeb/index.php(17): require('/usr/www/users/...') #9 {main} thrown in /usr/www/users/wrappeb/wp-content/plugins/brizy/twig-engine.php on line 34

**Comment by JacquesR** [comment] 2019-03-06 11:07
Same error on multiple websites using the Core theme from ThemeFuse and the Brizy plugin. Error goes away when disabling Brizzy, but then content of pages are of course broken. Latest and recent versions of Brizy are affected, and same issue on WP 4.9 and 5.0, and on latest PHP versions.
It may be caused by a database security update to:  5.5.5-10.1.38-MariaDB-1~jessie
Could you please test? 
https://mariadb.com/kb/en/library/mariadb-10138-release-notes/

**Comment by ImmortalPanda** [comment] 2019-03-06 13:00
Recently a bunch of websites that I made using Brizy and Brizy Pro completely stopped working. I couldn't even access the WP Admin page, kept on saying the page isn't working and that (domian name) currently isn't able to handle the request.
I contacted the Web Hosting company and they confirmed that over the past 2 days more than 100 database errors was logged.

**Comment by JacquesR** [comment] 2019-03-06 18:30
Follow-up. This does not seem to have been caused by the database update, but not sure.
Does the Brizy plugin or any part of it, have any automatic background updates?

**Comment by Brucekib** [comment] 2019-03-06 18:33
Here is a temporary fix:

Install the plugin Responsive Menu. Brizy will start working again.

To hide the hamburger Icon on the front end set the Breakpoint on the settings page to a low number e.g. 10.

Have installed and tested on a clean install and on existing sites and all works again.

**Comment by JacquesR** [comment] 2019-03-06 18:44
Your temporary fix works! :)
How did you stumble upon this seemingly random solution?

**Comment by Brucekib** [comment] 2019-03-06 18:46
I had a website that was working, the only difference was in the plugins installed. I noticed that disabling all the plugins except Brizy crashed the site. Then turned them on one at a time until Brizy worked again.

**Comment by Marktheron** [comment] 2019-03-06 22:10
Thank you! This worked perfectly!

**Comment by ImmortalPanda** [comment] 2019-03-07 06:41
Hope has been restored! Thank you for the fix, even though it's just temporary.. Hoping it stays fixed from here on

**Comment by NataliaBB** [comment] 2019-03-07 12:33
Hello everyone! @Brucekib @ImmortalPanda @JacquesR @Marktheron 
Many apologies for this problem. We are working the fix this issue asap. 
Will come with an update later.

Thank you!
Regards, Natalia

**Comment by JacquesR** [comment] 2019-03-08 08:13
Thank you @NataliaBB 
This update fixes the issue:
1.0.64 – 2019-03-07
Fixed: Autoloader compatibility

**Comment by Marktheron** [comment] 2019-03-08 19:30
Thank you very much @NataliaBB !

**Comment by Brucekib** [comment] 2019-03-08 19:33
Thank you @NataliaBB !

**Comment by NataliaBB** [comment] 2019-03-11 11:08
Thank you all!

**Comment by NataliaBB** [comment] 2019-03-11 11:08
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Closed by NataliaBB** 2019-03-11 11:08 UTC
Labels: bug
