### ISSUE TITLE
Formating text

### ISSUE THREAD

**Issue by LS25** [ThemeFuse/Brizy#12] opened 2018-05-09 11:39 UTC
How do I add paragraph spacing in Brizy? Please see the text in the Our Mission section of http://allsortadmin-co-uk.stackstaging.com/.

Thanks

Matt

**Comment by DimiBaitanciuc** [comment] 2018-05-09 12:11
Hey Matt, 

I think we've already covered that on our Facebook chat but I'll copy paste my answer here as well for future reference.

1. just hit enter to go to the next line this will naturally separate the text in paragraphs: http://jmp.sh/jIK97XX

2. Hit enter (this will create a new paragraph inside the same text block), and then play with the Gap Below option from the toolbar: http://jmp.sh/Tnj5DbL

**Comment by DimiBaitanciuc** [comment] 2018-05-09 12:29
Indeed, I'll push this forward to our development team. When the issue will be solved and closed you'll receive a notification from Github ;)

**Comment by LS25** [comment] 2018-05-10 07:40
Hi, 

I saw the issue on Chrome Version 66.0.3359.139 (Official Build) (64-bit) and in Safari Version 11.1 (13605.1.33.1.2) on my iMac. 

I have also noticed that if you view the website on mobile (both Android and iOS) the same text not only is missing the spacing but it is also centralised rather than being left justified. 

Heres the URL I am using:

[http://allsortadmin-co-uk.stackstaging.com/](http://allsortadmin-co-uk.stackstaging.com/)

It's the Our Mission section. 

Thanks

Matt

**Comment by bagrinsergiu** [comment] 2018-05-10 07:57
Thank you Matt

**Comment by bagrinsergiu** [comment] 2018-05-10 08:30
Q: I have also noticed that if you view the website on mobile (both Android and iOS) the same text not only is missing the spacing but it is also centralised rather than being left justified.

A: We have this issue in our to do list.

---

Q: I saw the issue on Chrome Version 66.0.3359.139 (Official Build) (64-bit) and in Safari Version 11.1 (13605.1.33.1.2) on my iMac.

A: I tested on PC, Mac ( Chrome, Firefox, Safari ). I can't reproduce it. We can try with a screen video.

Jing: https://www.techsmith.com/download/jing/
Jumpshare: https://jumpshare.com/downloading

**Comment by DimiBaitanciuc** [comment] 2018-05-11 19:48
@bagrinsergiu I've managed to reproduce it: http://jmp.sh/IprNSLD
I'll share login credentials on Monday and we'll take a look why this happens.

**Comment by LS25** [comment] 2018-05-11 19:51
Thanks for your efforts here! Much appreciated

**Comment by bagrinsergiu** [comment] 2018-05-31 12:28
@LS25 

This has been fixed and will be included in the next update 1.0.8 (24-48 hours)

Thank you for reporting
Sergiu

**Closed** 2018-05-31 12:29 UTC
Labels: bug
