### ISSUE TITLE
Brizy defaults to it's own template

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#89] opened 2018-06-05 00:55 UTC
I have noticed that Brizy always defaults to its own template even though the page template is saved from either the WordPress dashboard area or the page builder area itself. I am using the GeneratePress theme and if I tell Brizy to save the default page template to use in the page builder area and then exit the area and come back again, it keeps defaulting back to the Brizy template even though I have saved the page template to something else.

**Comment by bagrinsergiu** [comment] 2018-06-05 06:10
Hi @quantumleap33,

Thanks for letting us know, we are looking into it.

Sergiu

**Comment by quantumleap33** [comment] 2018-06-06 21:55
Great, thank you!

**Comment by bagrinsergiu** [comment] 2018-06-29 10:08
I can't reproduce this issue. Can you give me a video capture? Thanks

https://jumpshare.com/v/Wxd2I8iKLJ5Nhbxwvh1U

**Comment by quantumleap33** [comment] 2018-06-29 12:57
Ok I know why it works for you. I have GP Premium also installed and that creates extra issues which I will explain in a minute. But in your case, try the following: Create a new page, Pages->Add New. Set a title (the template is set as the Default Template by default), then publish. Now click "Edit with Brizy". The Brizy editor open with it's own template bypassing the previously default one from the theme. Setting the default template from there, then exiting and coming back again works as expected.

Now there are issue when GP Premium is installed all all the modules activated. I am not sure I am allowed to send you the plugin since it's a paid addon but you can contact Tom Usborne, the GeneratePress creator, he will be able to provide you withthe files. Now with the GP Premium activated, begin with the steps that I descibed previously. Brizy still bypasses the default template saved but not only that. When you exit to WordPress, there is no button to continue to edit with Brizy. Only a "Back to WordPress Editor" button is available. When you click on it, it takes you back to the WordPress editor. Clicking "Edit with Brizy from there", starts Brizy editor blank, all page changes have been lost and you have to start again.

**Comment by felipeozalmeida** [comment] 2019-02-20 14:22
I had the same problem, Brizy defaulting to its own page template (as i noted here #260) . Fortunately, I was able to recover to my previous template with your instructions, they were really helpful. Thanks.

**Comment by NataliaBB** [comment] 2020-03-05 12:02
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Closed by NataliaBB** 2020-03-05 12:02 UTC
Labels: bug, needs feedback
