### ISSUE TITLE
Birzy crashes on activating global element

### ISSUE THREAD

**Issue by 4him** [ThemeFuse/Brizy#116] opened 2018-06-09 19:13 UTC
I noticed some bugs - have updated to 1.0.9 and marked element as global. After that brizy crashed and didn't wanted to restart. Can't do anything on edit part of page - theres no control elements. Home page was broken and part of info lost. 
Solution was delete Birzy, logout, login and install old version of plugin. And update once again. After this I change element market as global to default.
Since this I would like to know how it possible to make an backup of page edited in brizy or transfer content from one page to other - to make it looks similar?

**Comment by bagrinsergiu** [comment] 2018-06-09 20:31
Hi @4him ,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment] 2018-06-11 08:30
I made a lot of tests on mac last 2 days and i can't reproduce this issue.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu

**Closed by bagrinsergiu** 2018-06-11 08:30 UTC
Labels: bug
