### ISSUE TITLE
[BUG] Posts archive pagination is broken

### ISSUE THREAD

**Issue by jwarnox** [ThemeFuse/Brizy#717] opened 2018-10-09 11:46 UTC
Hello,

We are using the Posts archive (Brizy Pro 0.0.10) showing 1 row of three posts filtered by date descending, but when you paginate to next page and next page, it only show the same first 3 posts eachtime?!

Can you advise please.

regards,
Jamie

**Comment by jwarnox** [comment] 2018-10-11 11:52
Screenshots to demonstrate, I have 6 posts:

Page 1

![screen shot 2018-10-11 at 12 51 36](https://user-images.githubusercontent.com/35316/46802157-7f361d80-cd54-11e8-936c-875d5e33372c.png)

And on Page 2

![screen shot 2018-10-11 at 12 51 49](https://user-images.githubusercontent.com/35316/46802170-865d2b80-cd54-11e8-913a-8a5155381c99.png)

the exact same posts?

**Comment by jwarnox** [comment] 2018-10-16 10:47
Hello,

I have a fix for this bug, the problem is in:

brizy-pro/content/placeholders/post-loop.php

The $paged parameter was not passed to the $params in the else statement - I have added paged => $paged, @ line 100 as below:

```
if ( $attributes['taxonomy'] == 'template' && $attributes['value'] == 'main_query' ) {
			global $wp_query;

			$queryVars                   = $wp_query->query_vars;
			$queryVars['orderby']        = isset( $attributes['orderby'] ) ? $attributes['orderby'] : 'none';
			$queryVars['order']          = isset( $attributes['order'] ) ? $attributes['order'] : 'ASC';
			$queryVars['posts_per_page'] = isset( $attributes['count'] ) ? $attributes['count'] : 3;
			$queryVars['paged']          = $paged;
			$query                       = new WP_Query( $queryVars );

		} else {
			$params = array(
				'tax_query'      => array(
					array(
						'taxonomy' => $attributes['taxonomy'],
						'field'    => 'term_id',
						'terms'    => $attributes['value']
					)
				),
				'posts_per_page' => isset( $attributes['count'] ) ? $attributes['count'] : 3,
				'orderby'        => isset( $attributes['orderby'] ) ? $attributes['orderby'] : 'none',
				'order'          => isset( $attributes['order'] ) ? $attributes['order'] : 'ASC',
				'paged'			 => $paged,
				'post_type'      => 'any',
			);
			
			$query  = new WP_Query( $params );
		}

```

Brizy team please test and roll in a fix

thanks,
Jamie

**Comment by dmccan** [comment] 2018-11-09 14:12
I have the same issue. Confirm it is still not working in Brizy 1.0.45 and Brizy Pro 0.0.12

**Comment by dmccan** [comment] 2018-11-25 04:17
I tested with 1.0.47 and 0.0.13 and the pagination is still broken.

**Comment by KyleAtDND** [comment] 2018-12-06 01:50
I can confirm still broken, I tested with a custom post type.

**Comment by bagrinsergiu** [comment] 2018-12-11 18:53
Hi all,

My tests environnement is:
Brizy Free: 1.0.52
Brizy Pro: 0.0.14

Post Archive (Post Element + Custom Post Type) Demo link: https://jmp.sh/WfNMozc

Sorry for the delay and thanks for reporting.
Can you confirm if it is working for you?
Sergiu

**Comment by KyleAtDND** [comment] 2018-12-11 20:09
I'm on all the latest and experiencing the same issue as reported above, but I think the difference (at least between what I'm doing and you're doing), is that this is occurring using the "Archives" block instead of the "Posts" block. From you demo, you did "Posts," whereas on my website which is still having the problem, I dragged over "Archives": http://cloud.designanddevelop.io/2e1360a3cd94.

**Comment by dmccan** [comment] 2018-12-12 00:09
Brizy 1.0.52 and Pro 0.0.14 still does not work. 

FWIW, the Posts module is not working either. It is only showing the 1st post.

**Comment by KyleAtDND** [comment] 2018-12-13 14:43
Ah, [resetting the permalinks](https://www.inmotionhosting.com/support/edu/wordpress/wordpress-features/reset-permalinks) fixed mine. @HQRaja & @dmccan, have you tried that since? Does it fix it for you?

**Comment by HQRaja** [comment] 2018-12-13 15:18
@KyleAtDND Thanks for the suggestion...saving the permalinks again has fixed it for me too.

@bagrinsergiu Although this isn't super-important, is there a way to change the '/bpage/' part that appears in URLs for pagination to something else like /page/ or /p/ ?

**Comment by KyleAtDND** [comment] 2018-12-13 15:34
@HQRaja, I agree that the "/bpage/" is a little weird looking. I assume you don't use "/page/" because that interferes with the wordpress query, but replacing "bpage' with something that is just a one-word (or letter) descriptor (such as "/p/") would be nice.

**Comment by HQRaja** [comment] 2018-12-13 16:22
@KyleAtDND Exactly...'bpage' just looks and sounds too weird. I think /p/ would be great, or just letting users choose what they want (optionally).

**Comment by dmccan** [comment] 2018-12-13 22:53
Pagination works if you refresh permalinks. 

Brizy team - if you are creating a new permalink structure then you can refresh the permalinks in code:  

`flush_rewrite_rules();`

**Comment by bagrinsergiu** [comment] 2018-12-14 11:02
> Pagination works if you refresh permalinks.
> 
> Brizy team - if you are creating a new permalink structure then you can refresh the permalinks in code:
> 
> `flush_rewrite_rules();`

We added it on install and update: https://jmp.sh/x9feQ7m
It is not working with copy/ paste. 

`flush_rewrite_rules();` - use a lot of resources. We don't want to add `flush_rewrite_rules();` on each admin page refresh. 

Thanks for your help. 
Sergiu

**Comment by bagrinsergiu** [comment] 2018-12-14 11:04
Hi @KyleAtDND and @HQRaja 

Thanks for details. I added a new issue regarding page slug /bpage/ 

Thanks for reporting.
Sergiu

**Comment by bagrinsergiu** [comment] 2018-12-14 11:05
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Closed by bagrinsergiu** 2018-12-14 11:05 UTC
Labels: Dynamic Content, bug
